######################
# MSSQL Database Configuration
######################
quarkus.datasource.db-kind=mssql
quarkus.datasource.metrics.enabled=true
quarkus.datasource.jdbc.additional-jdbc-properties.encrypt=false
quarkus.datasource.jdbc.additional-jdbc-properties.trustServerCertificate=true
quarkus.datasource."read-only".db-kind=mssql
quarkus.datasource."read-only".jdbc.additional-jdbc-properties.encrypt=false
quarkus.datasource."read-only".jdbc.additional-jdbc-properties.trustServerCertificate=true
quarkus.datasource."read-only".jdbc.additional-jdbc-properties.sendStringParametersAsUnicode=false
quarkus.datasource."read-only".jdbc.additional-jdbc-properties.applicationIntent=readOnly
# DevServices configuration
quarkus.compose.devservices.files=${user.dir}/docker/docker-compose.yaml
quarkus.compose.devservices.reuse-project-for-tests=true
